pipelines:
  branches:
    master:
      - step:
          name: Initialization
          script:
            - echo "Further steps require manual trigger"
      - step:
          name: Deploy React App
          trigger: manual
          deployment: production
          script:
            - pipe: atlassian/sftp-deploy:0.9.0
              variables:
                USER: $SFTP_USER
                SERVER: $SFTP_HOST
                REMOTE_PATH: $SFTP_REMOTE_PATH
                LOCAL_PATH: $BUILD_PATH
                SSH_KEY: $SFTP_KEY